import arcade
class SceneBase(arcade.Window):
    def _init_(self, width, height, title)
        super()._init_(width, height, title, update_rate=1/120)
        arcade.set_background_color(arcade.color_from_hex_string("#121216"))
        def on_draw(self): ...
        def on_update(self, delta_time: float): ...
        def on_key_press(self, symbol: int, modifiers: int): ...
        def on_key_release(self, symbol: int, modifiers: int): ...